version: '2'
services:
    timetrack-app:
        image: timetrack
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://timetrack-mysql:3306/timetrack?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timetrack-mysql:
        extends:
            file: mysql.yml
            service: timetrack-mysql
